spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trade_finance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: halogen1
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

server:
  error:
    include-stacktrace: never
    include-message: always